export const CHANGE_INPUT_VALUE = "change_input_value"
export const UPDATE_TODO_LIST = "update_todo_list"
export const DELETE_TODO_ITEM = "delete_todo_item"
export const INIT_LIST = "init_list"
export const GET_INTI_LIST = "get_inti_list"